name: Vraag / support
description: Stel een vraag over IrenePro
title: "[QUESTION] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Vraag
      placeholder: Stel hier je vraag
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context

  - type: input
    id: company
    attributes:
      label: Bedrijfsnaam
      placeholder: Namens welk bedrijf wordt de vraag gesteld
  
  - type: input
    id: contact
    attributes:
      label: Contact informatie
      placeholder: Naam of email adres van de contact persoon
